#!/usr/bin/env python3.11
from pathlib import Path

from coordinates import get_coordinates
from weather_api_service import get_weather
from exceptions import ApiServiceError, CantGetCoordinates
from weather_formatter import format_weather
from history import save_weather, JSONFileWeatherStorage # PlainFileWeatherStorage


def main():
    try:
        coordinates = get_coordinates()
    except CantGetCoordinates:
        print("Не вдалося отримати GPS коордиати!")
        exit(1)
    try:
        weather = get_weather(coordinates)
    except ApiServiceError:
        print(f"Не вдалося отримати прогноз погоди по GPS координатам: "
              f"Latitude = {coordinates.latitude}"
              f"Longitude = {coordinates.longitude}")
        exit(1)
    print(format_weather(weather))

    save_weather(weather,
                 # PlainFileWeatherStorage(Path.cwd() / "history.txt")
                JSONFileWeatherStorage(Path.cwd() / "history.json")
                )


if __name__ == '__main__':
    main()


